name: countries_flutter
description: A new Flutter package project.
version: 0.0.1
homepage: https://github.com/tsinis/sealed_world/packages/countries_flutter

environment:
  sdk: '>=3.0.0-85.0.dev <4.0.0'
  flutter: ">=3.7.0-15"

dependencies:
  countries_dart:
    path: ../countries_dart
  currencies_dart:
    path: ../currencies_dart
  flutter:
    sdk: flutter


dev_dependencies:
  dart_code_metrics: ^5.4.0 # Flutter Favorite
  flutter_test: # From Google
    sdk: flutter
  lints: ^2.0.1 # From Google