name: currencies_dart
# provide description of this package:
description: Provides data for world currencies in the form of sealed classes.
version: 0.0.1

environment:
  sdk: '>=3.0.0-136 <4.0.0'

dev_dependencies:
  dart_code_metrics: ^5.4.0 # Flutter Favorite
  lints: ^2.0.1 # From Google
  test: ^1.22.2 # From Google
