name: publish_to_pub_workflow

on:
  workflow_call:
    inputs:
      package_name:
        required: true
        type: string
      tag:
        required: true
        type: string

jobs:
  check-package-version:
    name: ⏳ Publish ${{ inputs.tag }} Package
    if: ${{ github.event_name == 'push' && github.actor == 'tsinis' }}
    runs-on: ubuntu-latest
    timeout-minutes: 10
    env:
      package_name: ${{ inputs.tag }}
    outputs:
      package_name: ${{ steps.set_package.outputs.package_name }}
    steps:
      - name: Extract package name
        id: set_package
        run: echo "package_name=$(echo ${{ inputs.tag }} | cut -d '-' -f1)" >> $GITHUB_OUTPUT

      - name: Set working directory
        run: echo "relative_path=packages/${{ env.package_name }}" >> $GITHUB_ENV

      - name: 📚 Git checkout
        uses: actions/checkout@v4.2.2

      - name: 1️⃣ Set version tag
        run: |
          VERSION_TAG=$(echo "${{ inputs.tag }}" | grep -oE '${{ env.package_name }}-v([0-9]+.[0-9]+.[0-9]+)' | grep -oE '[0-9]+\.[0-9]+\.[0-9]+')
          echo "TAG=${VERSION_TAG}" >> $GITHUB_ENV
        shell: /bin/bash -e {0}
        env:
          relative_path: ${{ env.relative_path }}

      - name: 2️⃣ Get version from pubspec.yaml
        run: |
          PUBSPEC_VERSION=$(sed -n '1 s/version: *//p' pubspec.yaml)
          echo "PUBSPEC=${PUBSPEC_VERSION}" >> $GITHUB_ENV

      - name: 3️⃣ Get version from CHANGELOG.md
        run: |
          CHANGELOG_VERSION=$(sed -n '1 s/^## *//p' CHANGELOG.md)
          echo "CHANGELOG=${CHANGELOG_VERSION}" >> $GITHUB_ENV

      - name: 🆚 Check if versions match
        run: |
          echo "Tag version: ${{ env.TAG }}"
          echo "pubspec.yaml version: ${{ env.PUBSPEC }}"
          echo "CHANGELOG.md version: ${{ env.CHANGELOG }}"

      - name: ❌ Delete tag if version is not same as tag
        uses: dev-drprasad/delete-tag-and-release@v1.1
        if: ${{ env.PUBSPEC != env.CHANGELOG || env.PUBSPEC != env.TAG || env.CHANGELOG != env.TAG }}
        with:
          tag_name: ${{ inputs.tag }}
          delete_release: false
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: 🚫 Cancel workflow if tag is not the same as version
        uses: andymckay/cancel-action@0.5
        if: ${{ env.PUBSPEC != env.CHANGELOG || env.PUBSPEC != env.TAG || env.CHANGELOG != env.TAG }}

      - name: 💤 Sleep for 10 seconds
        run: sleep 10s
        shell: bash

  publish:
    name: 📝 Publish to pub.dev
    needs: check-package-version
    if: ${{ github.repository_owner == 'tsinis' && github.actor == 'tsinis' }}
    uses: dart-lang/setup-dart/.github/workflows/publish.yml@main
    with:
      environment: "pub.dev"
      working-directory: packages/${{ needs.check-package-version.outputs.package_name }}
