name: publish_packages

on:
  push:
    branches: [main]
    tags:
      - '[a-z0-9]+_[a-z]+-v[0-9]+\.[0-9]+\.[0-9]+'

jobs:
  publish:
    if: github.ref_type == 'tag'
    runs-on: ubuntu-latest
    timeout-minutes: 5
    permissions:
      id-token: write
    steps:
      - name: Git Checkout
        uses: actions/checkout@v4.2.2

      - name: Extract Package Name
        id: extract_package_name
        run: |
          echo "package_name=$(echo ${{ github.ref_name }} | cut -d '-' -f1)" >> $GITHUB_OUTPUT

      - name: Publish
        uses: ./.github/workflows/publish_to_pub_workflow.yaml
        with:
          package_name: ${{ steps.extract_package_name.outputs.package_name }}
          tag: ${{ github.ref_name }}
