name: publish_to_pub

on:
  push:
    branches: [main]
    tags:
    - 'sealed_languages-v[0-9]+.[0-9]+.[0-9]+*'

jobs:
  publish:
    if: github.ref_type == 'tag'
    uses: ./.github/workflows/publish_to_pub.yaml
    with:
      package_name: sealed_languages
      tag: ${{ github.ref }}