name: publish_to_pub

on:
  workflow_call:
    inputs:
      package_name:
        required: true
        type: string
      tag:
        required: true
        type: string

jobs:
  check-package-version:
    env:
      relative_path: packages/${{ inputs.package_name }}
    name: ⏳ Publish ${{ inputs.package_name }} Package
    if: ${{ github.event_name == 'push' && github.actor == 'tsinis' }}
    defaults:
      run:
        working-directory: ${{ env.relative_path }}

    runs-on: "ubuntu-latest"
    timeout-minutes: 10

    steps:
      - name: 📚 Git checkout
        uses: actions/checkout@v3


      - name: 1️⃣ Get version from pubspec.yaml
        run: |
          PUBSPEC_VERSION=$(sed -n '1 s/version: *//p' pubspec.yaml)
          echo "PUBSPEC=${PUBSPEC_VERSION}" >> $GITHUB_ENV

      - name: 2️⃣ Get version from CHANGELOG.md
        run: |
          CHANGELOG_VERSION=$(sed -n '1 s/^## *//p' CHANGELOG.md)
          echo "CHANGELOG=${CHANGELOG_VERSION}" >> $GITHUB_ENV

      - name: 🆚 Check if versions match
        run: |
          echo "pubspec.yaml version: ${{ env.PUBSPEC }}"
          echo "CHANGELOG.md version: ${{ env.CHANGELOG }}"
          echo "Tag version: ${{ inputs.tag }}"

      - name: Delete tag if version is not same as tag
        uses: dev-drprasad/delete-tag-and-release@v0.2.1
        if: ${{ env.PUBSPEC != env.CHANGELOG || env.PUBSPEC != inputs.tag || env.CHANGELOG != inputs.tag }}
        with:
          tag_name: ${{ inputs.package_name }}-v${{ inputs.tag }}
          delete_release: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: 🚫 Cancel workflow if tag is not the same as version
        uses: andymckay/cancel-action@0.3
        if: ${{ env.PUBSPEC != env.CHANGELOG || env.PUBSPEC != inputs.tag || env.CHANGELOG != inputs.tag }}

      - name: Sleep for 10 seconds
        run: sleep 10s
        shell: bash

  publish:
      name: 📝 Publish to pub.dev
      needs: check-package-version
      if: ${{ github.repository_owner == 'tsinis' && github.actor == 'tsinis' }}
      uses: dart-lang/setup-dart/.github/workflows/publish.yml@v1
      with:
        environment: pub.dev
        working-directory: packages/${{ inputs.package_name }}
