name: publish_to_pub

on:
  push:
    branches: [main]
    tags:
    - 'sealed_languages-v[0-9]+.[0-9]+.[0-9]+*'

jobs:
  get-version-from-tag:
    runs-on: ubuntu-latest
    steps:
      - name: Calculate version tag
        run: |
          VERSION_TAG=$(echo "${{ github.ref }}" | grep -oE 'sealed_languages-v([0-9]+.[0-9]+.[0-9]+)' | grep -oE '[0-9]+\.[0-9]+\.[0-9]+')
          echo "VERSION_TAG=${VERSION_TAG}" >> $GITHUB_ENV

  verify-languages-dart:
    needs: get-version-from-tag
    uses: ./.github/workflows/publish_to_pub.yaml
    with:
      package_name: sealed_languages
      version_tag: ${{ env.VERSION_TAG }}