name: publish_to_pub

on:
  push:
    branches: [main]
    tags:
    - 'sealed_languages-v[0-9]+.[0-9]+.[0-9]+*'

jobs:
  get-version-from-tag:
    runs-on: ubuntu-latest
    outputs:
      version_tag: ${{ steps.calculate-version-tag.outputs.version_tag }}
    steps:
      - name: Calculate version tag
        id: calculate-version-tag
        run: |
          VERSION_TAG=$(echo "${{ github.ref }}" | grep -oE 'sealed_languages-v([0-9]+.[0-9]+.[0-9]+)' | grep -oE '[0-9]+\.[0-9]+\.[0-9]+')
          echo "version_tag=${VERSION_TAG}" >> "$GITHUB_OUTPUT"

  verify-languages-dart:
    needs: get-version-from-tag
    uses: ./.github/workflows/publish_to_pub.yaml
    with:
      package_name: sealed_languages
      version_tag: "${{ needs.get-version-from-tag.outputs.version_tag }}"